### ISSUE TITLE
Problem with OpenTK version

### ISSUE THREAD

**Issue by sourceskyboxer** [Nihlus/GLWidgetTest#1]
Hello I got errors of example but i tried to compile with Visual Studio 2017 Community and it shows error 24/25 How do I fix?
If I update from nutget servers like GTKSharp3 and OpenTK 2.0

But GLWidget gots unusable classes If I compile and It doesn't recognize compile. 
Please fix for new version thanks

**Comment by Nihlus** [comment]
This is not a support forum. Please create a more detailed and specific bug report or ask on Gitter.

**Comment by Nihlus** [comment]
Hello there. This is an example project used for testing and prototyping, and it isn't supported software. Most of the changes in this repository are awaiting a merge with the main OpenTK repository.

Furthermore, the only functional project in the repository targets GTK3.

**Comment by sourceskyboxer** [comment]
Okay no problem. I have fixed it :) Don't worry!
